-- MySQL Script generated by MySQL Workbench
-- Tue May 21 14:28:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tpi_lqa_dbstage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpi_lqa_dbstage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpi_lqa_dbstage` DEFAULT CHARACTER SET utf8 ;
USE `tpi_lqa_dbstage` ;

-- -----------------------------------------------------
-- Table `tpi_lqa_dbstage`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_lqa_dbstage`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `type` TINYINT(1) NOT NULL,
  `account_status` INT NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi_lqa_dbstage`.`branchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_lqa_dbstage`.`branchs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi_lqa_dbstage`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_lqa_dbstage`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(23) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi_lqa_dbstage`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_lqa_dbstage`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi_lqa_dbstage`.`internships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_lqa_dbstage`.`internships` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `max_people` TINYINT NOT NULL,
  `number_registrants` INT NULL,
  `branchs_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `teachers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) INVISIBLE,
  UNIQUE INDEX `Unique` (`name` ASC, `start_date` ASC) INVISIBLE,
  INDEX `fk_internships_branchs_idx` (`branchs_id` ASC) VISIBLE,
  INDEX `fk_internships_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_internships_teachers1_idx` (`teachers_id` ASC) VISIBLE,
  CONSTRAINT `fk_internships_branchs`
    FOREIGN KEY (`branchs_id`)
    REFERENCES `tpi_lqa_dbstage`.`branchs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internships_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `tpi_lqa_dbstage`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internships_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `tpi_lqa_dbstage`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi_lqa_dbstage`.`childs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_lqa_dbstage`.`childs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_childs_Users1_idx` (`Users_id` ASC) VISIBLE,
  UNIQUE INDEX `Unique` (`first_name` ASC, `last_name` ASC) VISIBLE,
  CONSTRAINT `fk_childs_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `tpi_lqa_dbstage`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpi_lqa_dbstage`.`childs_register_internships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpi_lqa_dbstage`.`childs_register_internships` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `childs_id` INT NOT NULL,
  `internships_id` INT NOT NULL,
  INDEX `fk_childs_has_internships_internships1_idx` (`internships_id` ASC) VISIBLE,
  INDEX `fk_childs_has_internships_childs1_idx` (`childs_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `unique` (`childs_id` ASC, `internships_id` ASC) VISIBLE,
  CONSTRAINT `fk_childs_has_internships_childs1`
    FOREIGN KEY (`childs_id`)
    REFERENCES `tpi_lqa_dbstage`.`childs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_childs_has_internships_internships1`
    FOREIGN KEY (`internships_id`)
    REFERENCES `tpi_lqa_dbstage`.`internships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
